<?php
/**
 * InvoiceResponseActionsTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EConnect\Psb\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * InvoiceResponseActionsTest Class Doc Comment
 *
 * @category    Class
 * @description Expectations towards the seller    [NOA] No action required.    [PIN] Provide information. Missing information requested without re-issuing invoice.    [NIN] Issue new invoice. Request to re-issue a corrected invoice.    [CNF] Credit fully. Request to fully cancel the referenced invoice with a credit note.    [CNP] Credit partially. Request to issue partial credit note for corrections only.    [CNA] Credit the amount. Request to repay the amount paid on the invoice.     [OTH] Other. Requested action is not defined by code.                  Status Clarification Action list:  ./misc/codeList.html#status-clarification-action
 * @package     EConnect\Psb
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InvoiceResponseActionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InvoiceResponseActions"
     */
    public function testInvoiceResponseActions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "noa"
     */
    public function testPropertyNoa()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pin"
     */
    public function testPropertyPin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nin"
     */
    public function testPropertyNin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cnf"
     */
    public function testPropertyCnf()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cnp"
     */
    public function testPropertyCnp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cna"
     */
    public function testPropertyCna()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "oth"
     */
    public function testPropertyOth()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
