<?php
/**
 * InvoiceResponseReasonsTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EConnect\Psb\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * InvoiceResponseReasonsTest Class Doc Comment
 *
 * @category    Class
 * @description Depending on the status code, a clarification may be needed to state the buyer’s reason for the status.                [NON] No Issue. Indicates that receiver of the documents sends the message just to update the status and there are no problems with document processing.    [REF] References incorrect. Indicates that the received document did not contain references as required by the receiver for correctly routing the document for approval or processing.    [LEG] Legal information incorrect. Information in the received document is not according to legal requirements.    [REC] Receiver unknown. The party to which the document is addressed is not known.    [QUA] Item quality insufficient. Unacceptable or incorrect quality.    [DEL] Delivery issues. Delivery proposed or provided is not acceptable.    [PRI] Prices incorrect. Prices not according to previous expectation.    [QTY] Quantity incorrect. Quantity not according to previous expectation.     [ITM] Items incorrect. Items not according to previous expectation.    [PAY] Payment terms incorrect. Payment terms not according to previous expectation.     [UNR] Not recognized. Commercial transaction not recognized.    [FIN] Finance incorrect. Finance terms not according to previous expectation.    [PPD] Partially Paid. Payment is partially but not fully paid.     [OTH] Other. Reason for status is not defined by code.                  Status Clarification Reason list:  ./misc/codeList.html#status-clarification-reason
 * @package     EConnect\Psb
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InvoiceResponseReasonsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InvoiceResponseReasons"
     */
    public function testInvoiceResponseReasons()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "non"
     */
    public function testPropertyNon()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ref"
     */
    public function testPropertyRef()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "leg"
     */
    public function testPropertyLeg()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cnf"
     */
    public function testPropertyCnf()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rec"
     */
    public function testPropertyRec()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qua"
     */
    public function testPropertyQua()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "del"
     */
    public function testPropertyDel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pri"
     */
    public function testPropertyPri()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qty"
     */
    public function testPropertyQty()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "itm"
     */
    public function testPropertyItm()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pay"
     */
    public function testPropertyPay()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unr"
     */
    public function testPropertyUnr()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fin"
     */
    public function testPropertyFin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ppd"
     */
    public function testPropertyPpd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "oth"
     */
    public function testPropertyOth()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
