<?php
/**
 * PartyPermissionsTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EConnect\Psb\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PartyPermissionsTest Class Doc Comment
 *
 * @category    Class
 * @description PartyPermissions
 * @package     EConnect\Psb
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PartyPermissionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PartyPermissions"
     */
    public function testPartyPermissions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "can_send_document"
     */
    public function testPropertyCanSendDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "can_receive_document"
     */
    public function testPropertyCanReceiveDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "can_remove_document"
     */
    public function testPropertyCanRemoveDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "can_manage_hook"
     */
    public function testPropertyCanManageHook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "can_change_document_status"
     */
    public function testPropertyCanChangeDocumentStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
