<?php
/**
 * PurchaseInvoiceApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EConnect\Psb\Test\Api;

use \EConnect\Psb\Configuration;
use \EConnect\Psb\ApiException;
use \EConnect\Psb\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PurchaseInvoiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PurchaseInvoiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deletePurchaseInvoice
     *
     * Delete purchase invoice..
     *
     */
    public function testDeletePurchaseInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadPurchaseInvoice
     *
     * Download purchase invoice..
     *
     */
    public function testDownloadPurchaseInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPurchaseInvoiceStatuses
     *
     * Get purchase invoice statuses..
     *
     */
    public function testGetPurchaseInvoiceStatuses()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recognizePurchaseInvoice
     *
     * Recognize purchase invoice..
     *
     */
    public function testRecognizePurchaseInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendInvoiceResponse
     *
     * Send invoice response to let the seller know the status of the received invoice..
     *
     */
    public function testSendInvoiceResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
