<?php
/**
 * SalesInvoiceApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EConnect\Psb\Test\Api;

use \EConnect\Psb\Configuration;
use \EConnect\Psb\ApiException;
use \EConnect\Psb\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SalesInvoiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SalesInvoiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getSalesInvoiceStatuses
     *
     * Get sales invoice statuses..
     *
     */
    public function testGetSalesInvoiceStatuses()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for queryRecipientPartyForSalesInvoice
     *
     * Lookup the recipient party in Peppol..
     *
     */
    public function testQueryRecipientPartyForSalesInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recognizeSalesInvoice
     *
     * Recognize sales invoice..
     *
     */
    public function testRecognizeSalesInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendSalesInvoice
     *
     * Send an invoice..
     *
     */
    public function testSendSalesInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
